### ISSUE TITLE
[BUG]: duplicate package-lock.json

### ISSUE THREAD

**Issue by lwaekfjlk** [lwaekfjlk/gpu-bartender#26]
### Description of the bug

The package-lock.json both exist in the frontend folder and the root folder

### Steps To Reproduce

duplicate

**Comment by lwaekfjlk** [comment]
@YuanhuanO I checked OpenDevin's frontend. There UI needs to cd frontend and run things. Correspondingly, their package.json is inside the frontend folder.

**Comment by YuanhuanO** [comment]
> @YuanhuanO I checked OpenDevin's frontend. There UI needs to cd frontend and run things. Correspondingly, their package.json is inside the frontend folder.

I have edited in the last pr, maybe this issue can be closed?
